// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_hZhfRAvgDk39ZtJlXt7twFZmrT2S2xA',
    appId: '1:88216206511:web:af552c18f3b7c4da72a85a',
    messagingSenderId: '88216206511',
    projectId: 'zigocloudincomingcall',
    authDomain: 'zigocloudincomingcall.firebaseapp.com',
    storageBucket: 'zigocloudincomingcall.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-fVPQd5D_mZgYwRrU80z0i0vvIODtGI',
    appId: '1:88216206511:android:de162008b4721d5f72a85a',
    messagingSenderId: '88216206511',
    projectId: 'zigocloudincomingcall',
    storageBucket: 'zigocloudincomingcall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgpJxYb-9ymZ2OkBU7l5PIgNbMGLP5gA4',
    appId: '1:88216206511:ios:de952de1d6c98e0772a85a',
    messagingSenderId: '88216206511',
    projectId: 'zigocloudincomingcall',
    storageBucket: 'zigocloudincomingcall.appspot.com',
    iosBundleId: 'com.example.offlineCallInvitation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgpJxYb-9ymZ2OkBU7l5PIgNbMGLP5gA4',
    appId: '1:88216206511:ios:de952de1d6c98e0772a85a',
    messagingSenderId: '88216206511',
    projectId: 'zigocloudincomingcall',
    storageBucket: 'zigocloudincomingcall.appspot.com',
    iosBundleId: 'com.example.offlineCallInvitation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_hZhfRAvgDk39ZtJlXt7twFZmrT2S2xA',
    appId: '1:88216206511:web:361071027842f46f72a85a',
    messagingSenderId: '88216206511',
    projectId: 'zigocloudincomingcall',
    authDomain: 'zigocloudincomingcall.firebaseapp.com',
    storageBucket: 'zigocloudincomingcall.appspot.com',
  );
}
